### ISSUE TITLE
Saving (and general documentation)

### ISSUE THREAD

**Issue by wibbuffey** [js-emulators/desmond#2]
The library has almost **no** documentation, and it's not quite functional -- there's no way to save anything to LocalStorage (or at least return the current save data), no way to change controls, etc.

**Comment by Unzor** [comment]
Desmond's only functions are loadURL() and loadBlob(). There is not much documentation needed as there are barely any functions. You cannot save state using Desmond afaik.

**Comment by wibbuffey** [comment]
@Unzor Good point; was asking if there was a way to implement it considering `desmume-wasm` is a direct port of DeSmuME. I'll look into it later today and open a PR if it is.
