### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by DarkShadow8700** [js-emulators/desmond#3]
Hi I stumbled upon this emulator and I think it has high hopes for it but there is one thing   I'm wondering if controller support will be added to this emulator

**Comment by Unzor** [comment]
What do you mean by "Controller Support"? If you mean using a controller to use Desmond, you will have to do it yourself using WebHID and connecting your Xbox/Wii/whatever controller to your computer. I will have to add the "pressKey" function first, though. Not doing it now, will do it soon though.

**Comment by Unzor** [comment]
Closing this, feel free to reopen.
