### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by olijeffers0n** [js-emulators/desmond#4]
Hi, Thanks for porting this to something so easy to use.

I wondered if you had any intention of adding the ability to save easily? This would be super useful. Also, is it possible to use cheat codes with this? I would like to be able to unlock some levels in a game like Mario kart.

Thanks!

**Comment by Unzor** [comment]
I am not the original person who ported DeSmuME. The original project is at [DeSmuME-wasm](https://github.com/44670/desmume-wasm), as stated multiple times in the description, README, and site. This is just a fork of it to easily embed it to a website. DeSmuME-wasm has saving but Desmond does not. AFAIK there are no cheat codes in DeSmuME-wasm. See #2.

**Comment by Unzor** [comment]
I have found that there are now cheat codes in DeSmuME-wasm in the Early Access page, but I am not enabling them in Desmond. Go here:
http://ds.44670.org/
Closing this.
