### ISSUE TITLE
You cant save

### ISSUE THREAD

**Issue by eclipse-5214-2** [js-emulators/desmond#6]
I used desmond on one of my websites (ndsemu.glitch.me) and you cant save your ingame progress in a game. is there a fix?

**Comment by Unzor** [comment]
No, for some reason saving does not work on Desmond. You can try copying the source of [ds.44670.org](https://ds.44670.org) and all of the files, and embedding should probably work. (Remember, Desmond is just a way to make embeddability of NDS emulators easier.)

**Comment by Eclipse-5214** [comment]
ohh ok

**Comment by BlueFalcon234** [comment]
@Eclipse-5214 @eclipse-5214-2 I don’t know you got response from Unzor (can’t read what he wrote), but did you figure out how to save and then have the save file?

**Comment by Midnite59** [comment]
How do you save again?
